export enum Dimension {
  UNDERSTANDING = "Understanding",
  INQUIRY = "Inquiry",
  PROCEDURAL = "Procedural",
  WONDER = "Wonder",
  CONSEQUENCE = "Consequence",
  META_COGNITION = "Meta-Cognition",
  CREATIVE = "Creative",
  CAUSAL = "Causal",
  INTERACTIVE = "Interactive",
  GROUNDING = "Grounding",
  INTENT_SYNTHESIS = "Intent Synthesis",
  CODE_OBSERVATION = "CodeObservation",
}

export const DIMENSIONS_INFO: Record<Dimension, string> = {
  [Dimension.UNDERSTANDING]: "Understand and define the intent of the question or topic, to understand something or some behavior or process. you muse ask questions to understand the user intent. examples: what does he really mean by {prompt}? what actually is the user asking for? what is the user trying to achieve? what is the user trying to solve?",
  [Dimension.INQUIRY]: "find out why something is or acts like it does. to find out the facts, logic, evidence, philosophical, psychological and spiritual reasons why",
  [Dimension.PROCEDURAL]: "to know how to do something using current ideas, knowledge, information and concepts. Formulate methodology, strategy, and step-by-step implementation plans.",
  [Dimension.WONDER]: " to wonder about possibilities and scenerios and wonder about the outcomes of each wonder.Model counterfactual possibilities and 'What-if' scenarios.",
  [Dimension.CONSEQUENCE]: "Analyze impact, influence, and downstream effects of potential actions.",
  [Dimension.META_COGNITION]: "Think about the thoughts produced so far. Critically reflect on the reasoning, assumptions, and conclusions generated in previous steps.",
  [Dimension.CREATIVE]: "Exploring all the logical ways to solve a problem. developing new hypothesis. Think of new, lateral, or unconventional ways to solve issues, especially when encountering contradictions or dead-ends.",
  [Dimension.CAUSAL]: "Explain the fundamental cause behind a result, pattern, or phenomenon observed in the reasoning.",
  [Dimension.INTERACTIVE]: "Ask the user directly for more information, clarification, feedback, or decision support. Use this when the goals are ambiguous, when you need critical feedback on an architecture/concept, or when more constraints/requirements are needed from the user.",
  [Dimension.GROUNDING]: "Verify the truthfulness and factual accuracy of all reasoning conducted so far. Identify hallucinations, unverified assumptions, and unfounded claims. Break the system's overconfidence by grounding conclusions in evidence and reality. Evaluate whether the reasoning chain is built on truth or assumptions.",
  [Dimension.INTENT_SYNTHESIS]: "Distill all reasoning into a final, actionable technical directive.",
  [Dimension.CODE_OBSERVATION]: "A dedicated step injected by the engine when sandboxed code execution completes. Contains the actual stdout, stderr, exit code, and elapsed time from the Docker sandbox. Treat this data as ground truth — do NOT speculate about what code might output.",
};

export interface ThoughtPart {
  text?: string;
  inlineData?: {
    mimeType: string;
    data: string;
  };
}

// ── Async Code Side-Channel Types ──────────────────────────────────────────

export interface CodeRequest {
  id: string;                                            // UUID
  language: "python3" | "javascript";
  code: string;                                          // Full source
  createdAt: number;                                     // Date.now()
  status: "pending" | "launched" | "completed" | "timeout";
}

export interface CodeResult {
  requestId: string;                                     // Matches CodeRequest.id
  stdout: string;
  stderr: string;
  exitCode: number;
  elapsedMs: number;
}

// ───────────────────────────────────────────────────────────────────────────

export interface DebateRound {
  round: 1 | 2 | 3;
  internal: string;
  archival: string;
  external: string;
}

export interface ThoughtStep {
  dimension: Dimension;
  question: string;
  answers: {
    internal: string;
    archival: string;
    external: string;
  };
  controllerDecision?: {
    nextDimension: Dimension | "TERMINATE";
    reasoning: string;
  };
  /** Set when an answering agent emits an execute_code tool call. */
  codeRequest?: CodeRequest;
  /** Set on a CODE_OBSERVATION step injected by the engine after execution. */
  codeResult?: CodeResult;
  

  /** Full debate transcript when debate mode is active */
  debateRounds?: DebateRound[];
  /** Whether debate protocol ran for this step */
  debateEnabled?: boolean;
  /** Meta Reasoning Agent audit output */
  metaReasoningAudit?: string;
  /** Deep monologue generated by the Thinking Agent (Main Thinker) */
  thinkingMonologue?: string;
  /** Final consolidated insight generated by the Thinking Agent */
  consolidatedInsight?: string;
}

export interface DimensionCluster {
  id: string;              // e.g. "cluster-1"
  label: string;           // e.g. "Problem Understanding"
  dimensions: Dimension[]; // Intended dimensions for this cluster
  goal: string;            // What this cluster should achieve
  status: "PENDING" | "IN_PROGRESS" | "COMPLETE" | "SKIPPED";
  deviation?: string;      // If the Micro Controller deviated, why
}

export interface MacroPlan {
  sessionGoal: string;     // High-level goal of the entire session
  clusters: DimensionCluster[];
  estimatedTurns: number;
  createdAt: number;
}


export interface SingleDimensionDecision {
  mode: "SINGLE";
  dimension: Dimension | "TERMINATE";
  reasoning: string;
}

export type ControllerDecision = SingleDimensionDecision;

export interface SynthesisResult {
  status: "COMPLETE" | "CONTINUE";
  content: string;
  nextDimension?: Dimension;
  newDirective?: string;
}

export interface GroundingResult {
  verifiedClaims: string[];
  questionableClaims: Array<{
    claim: string;
    issue: string;
    recommendation: string;
  }>;
  hallucinations: Array<{
    claim: string;
    reality: string;
    severity: "CRITICAL" | "MODERATE";
  }>;
  confidenceLevel: "HIGH" | "MODERATE" | "LOW";
  confidenceJustified: boolean;
  verdict: "NO_HALLUCINATIONS" | "MINOR_HALLUCINATIONS" | "REQUIRES_ATTENTION";
  report: string;
}

// ── DAG Reasoning Graph Types ──────────────────────────────────────────────

export interface GraphNode {
  id: string;                     // UUID for this node
  step: ThoughtStep;              // The reasoning step
  parentIds: string[];            // IDs of nodes this depends on (empty = root)
  childIds: string[];             // IDs of nodes this spawned
  branchLabel?: string;           // e.g. "Branch A", "Main Trunk"
  depth: number;                  // Distance from root
  timestamp: number;              // Date.now() when created
}

export interface ReasoningGraph {
  nodes: Map<string, GraphNode>;  // node.id → GraphNode
  rootIds: string[];              // Top-level node IDs
  activeHeadId: string;           // ID of the current "frontier" node
  metadata: {
    sessionId: string;
    createdAt: number;
    totalBranches: number;
    maxDepth: number;
    originalInput?: any;
    macroPlan?: MacroPlan;
    finalIntent?: string;
    finalReport?: string;
    audioBase64?: string;
    executionJobId?: string;
  };
}

function safeRandomUUID(): string {
  if (typeof globalThis !== 'undefined' && globalThis.crypto?.randomUUID) {
    return globalThis.crypto.randomUUID();
  }
  if (typeof window !== 'undefined' && window.crypto?.randomUUID) {
    return window.crypto.randomUUID();
  }
  return 'xxxxxxxx-xxxx-4xxx-yxxx-xxxxxxxxxxxx'.replace(/[xy]/g, (c) => {
    const r = (Math.random() * 16) | 0;
    const v = c === 'x' ? r : (r & 0x3) | 0x8;
    return v.toString(16);
  });
}

export class GraphUtils {
  /** Insert a new node as a child of one or more parents */
  static addNode(
    graph: ReasoningGraph,
    step: ThoughtStep,
    parentId: string | string[] | null,
    branchLabel?: string
  ): GraphNode {
    const parentIdsArray = Array.isArray(parentId) ? parentId : (parentId ? [parentId] : []);
    
    // For depth, use max depth of all parents + 1
    let depth = 0;
    if (parentIdsArray.length > 0) {
      depth = Math.max(...parentIdsArray.map(id => graph.nodes.get(id)?.depth ?? 0)) + 1;
    }

    const node: GraphNode = {
      id: safeRandomUUID(),
      step,
      parentIds: parentIdsArray,
      childIds: [],
      branchLabel,
      depth,
      timestamp: Date.now(),
    };
    
    graph.nodes.set(node.id, node);
    
    if (parentIdsArray.length === 0) {
      graph.rootIds.push(node.id);
    } else {
      parentIdsArray.forEach(pId => {
        const parent = graph.nodes.get(pId);
        if (parent) parent.childIds.push(node.id);
      });
    }
    
    graph.activeHeadId = node.id;
    graph.metadata.maxDepth = Math.max(graph.metadata.maxDepth, node.depth);
    return node;
  }

  /** Get the linear history from root to a given node (for context building) */
  static getAncestorChain(graph: ReasoningGraph, nodeId: string): ThoughtStep[] {
    const chain: ThoughtStep[] = [];
    let current = graph.nodes.get(nodeId);
    while (current) {
      chain.unshift(current.step);
      current = current.parentIds[0]
        ? graph.nodes.get(current.parentIds[0])
        : undefined;
    }
    return chain;
  }

  /** Serialize the graph to a JSON-serializable structure for SSE streaming */
  static serialize(graph: ReasoningGraph): object {
    return {
      nodes: Array.from(graph.nodes.entries()).map(([id, node]) => ({
        id,
        dimension: node.step.dimension,
        question: node.step.question,
        parentIds: node.parentIds,
        childIds: node.childIds,
        branchLabel: node.branchLabel,
        depth: node.depth,
        timestamp: node.timestamp,
      })),
      rootIds: graph.rootIds,
      activeHeadId: graph.activeHeadId,
      metadata: graph.metadata,
    };
  }
}
